DELETE FROM courses;

INSERT INTO courses (week_number, slug, title, description, category, level, duration_minutes, topics_count, rating) VALUES
(1, 'intro-ai-healthcare-african-contexts', 'Introduction to AI in Healthcare & African Contexts', 'Define AI, ML, and deep learning. African healthcare landscape and challenges. AI success stories: Uganda, Kenya, Egypt.', 'foundations', 'beginner', 360, 3, NULL),
(2, 'data-science-statistics-healthcare', 'Fundamentals of Data Science & Statistics for Healthcare', 'Healthcare data types: structured, imaging, genomic. Sensitivity, specificity, AUC-ROC. Data quality, bias, and African data gaps.', 'foundations', 'beginner', 360, 3, NULL),
(3, 'machine-learning-basics', 'Machine Learning Basics — Supervised & Unsupervised Learning', 'ML paradigms and common algorithms. The ML workflow: training, validation, testing.', 'foundations', 'beginner', 360, 2, NULL),
(4, 'ai-ethics-global-decolonised-african', 'AI Ethics — Global, Decolonised & African Perspectives', 'WHO, EU AI Act, OECD frameworks critiqued. Ubuntu philosophy and the CARE framework. Ethical dilemma debate: African healthcare scenarios.', 'ethics', 'intermediate', 360, 3, NULL),
(5, 'data-handling-privacy-governance', 'Data Handling, Privacy & Governance in African Healthcare', 'Kenya Data Protection Act 2019 applied. Privacy-preserving techniques: federated learning. Data governance and community-based models.', 'ethics', 'intermediate', 360, 3, NULL),
(6, 'diagnostic-algorithms-cdss', 'Diagnostic Algorithms & Clinical Decision Support Systems', 'How diagnostic AI works: pattern recognition and explainability. CDSS types and integration challenges. Case study: evaluating a malaria diagnostic AI at KNH.', 'clinical', 'intermediate', 360, 3, NULL),
(7, 'medical-imaging-ai', 'Medical Imaging & AI', 'CNNs, transfer learning, and image classification. Radiology, pathology, ophthalmology, obstetric ultrasound. Image interpretation lab: AI vs. expert radiologist.', 'clinical', 'intermediate', 360, 3, NULL),
(8, 'public-health-applications-surveillance', 'Public Health Applications & Surveillance', 'AI for outbreak prediction, maternal and child health. NCD risk, supply chain, and workforce AI. Simulation: managing a cholera outbreak with AI tools.', 'tools', 'intermediate', 360, 3, NULL),
(9, 'ai-tools-nlp-llms-healthcare', 'Practical AI Tools, NLP & Large Language Models in Healthcare', 'AI platforms for clinical and research use. NLP in clinical documentation, ICD coding, and adverse event detection. Multilingual NLP challenges for Kiswahili and African languages.', 'tools', 'advanced', 360, 3, NULL),
(10, 'ethics-regulation-future-capstone', 'Ethics, Regulation, Future of AI & Capstone Presentations', 'Kenya National AI Strategy, KMPDC, and WHO ethics frameworks. Career positioning: research, clinical exposure, AI literacy. Capstone project presentations to an expert panel.', 'tools', 'advanced', 360, 3, NULL);
